### ISSUE TITLE
hey, iceefoox, can you make a disscution??

### ISSUE THREAD

**Issue by DemonFemaleAlpha1** [SnesLover22/Offline-Downloads#1]
idk how and the old disscution was closed. 
oh btw, i subcribed to ur yt account. please make a disscution cause ive been bored and i want to chit chat, lol. 
cya

**Comment by SnesLover22** [comment]
hey this isn't how you message people.

**Comment by DemonFemaleAlpha1** [comment]
ik but its the only way cause i dont got no other chat things, plus i get
blocked cause me in school
